### PR TITLE
modules/zrtp: encrypt/decrypt RTCP packets

### PR DESCRIPTION
**Pull request by glenvt18**
Incoming RTCP packet's encrypt-flag is checked in libzrtp.

### CODE REVIEW

**Comment by alfredh** [comment]
many thanks for the patch, it is very useful.

here is an unrelated change:

BIN  modules/zrtp/.zrtp.c.swp


/alfred

**Comment by glenvt18** [comment]
@alfredh updated

**Comment by glenvt18** [comment]
UPDATE. Better packet filtering, more informative logging on send/receive.
@alfredh mind a review?

**Comment by alfredh** [comment]
many thanks :)

**Pull request merged**
