### PR TITLE
auframe: add timestamp

### PR DESCRIPTION
**Pull request by alfredh**
Add timestamp to audio frame. The clock-rate of the timestamp is in microseconds:

`#define AUDIO_TIMEBASE 1000000U`

Updated audio source modules:

* [x] alsa
* [x] aubridge
* [x] audiounit
* [x] aufile
* [x] avformat
* [x] coreaudio
* [ ] gst
* [ ] i2s
* [x] jack
* [ ] opensles
* [x] oss
* [x] portaudio
* [x] pulse
* [x] rst
* [ ] sndio
* [x] winwave

### CODE REVIEW

**Comment by alfredh** [comment]
The following modules needs also needs to be updated:

* gst
* i2s
* opensles
* sndio

Does anyone want to have a look at that ?

You need to set the audio timestamp field of this struct:

```c
/**
 * Defines a frame of audio samples
 */
struct auframe {
	int fmt;       /**< Sample format (enum aufmt)        */
	void *sampv;   /**< Audio samples (must be mem_ref'd) */
	size_t sampc;  /**< Total number of audio samples     */
	uint64_t timestamp;  /**< Timestamp in AUDIO_TIMEBASE units */
};
```

FYI: @cspiel1 @juha-h

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> The following modules needs also needs to be updated:
> 
> * gst
> * i2s
> * opensles
> * sndio

I looked at opensles, but unfortunately don't have a clue to what value
timestamp should be set in bqRecorderCallback and opensles_player_alloc
functions.

**Comment by alfredh** [comment]
if we cannot get the hardware timestamp, I think there are 2 options:

1. count the total number of samples, and convert to microseconds.
  See alsa_src.c for example

2. use `tmr_jiffies_usec`

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> if we cannot get the hardware timestamp, I think there are 2 options:

This gives time in usecs:
```
uint64_t getTimeUSec() {
    struct timestamp now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    return now.tv_sec*1000000U + now.tv_usec;
}
```
Would it qualify has hw timestamp?

**Comment by juha-h** [comment]
Here is another version, but it returns int64_t:
```
static int64_t getTimeUSec() {
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    return (int64_t)now.tv_sec*1000000U + now.tv_nsec / 1000;
}
```

**Comment by alfredh** [comment]
you can also use this function, it does the same thing:

```c
uint64_t tmr_jiffies_usec(void);
```

**Comment by juha-h** [comment]
So this would be the diff?
```
diff --git a/modules/opensles/recorder.c b/modules/opensles/recorder.c
index 824b45f..c47aa15 100644
--- a/modules/opensles/recorder.c
+++ b/modules/opensles/recorder.c
@@ -58,7 +58,8 @@ static void bqRecorderCallback(SLAndroidSimpleBufferQueueItf bq, void *context)
    struct auframe af = {
        .fmt   = AUFMT_S16LE,
        .sampv = st->sampv[st->bufferId],
-       .sampc = st->sampc
+       .sampc = st->sampc,
+       .timestamp = tmr_jiffies_usec()
    };
    (void)bq;
 
```

**Comment by alfredh** [comment]
yes, great. same as test ausrc mock:

https://github.com/alfredh/baresip/blob/master/test/mock/mock_ausrc.c#L40

**Comment by juha-h** [comment]
Unfortunately it turned out that after the timestamps were added,
baresip is crashing on all Androind phones that have 32 bit
armeabi-v7a cpu architecture:

********** Crash dump: **********
Build fingerprint: 'motorola/cedric/cedric:8.1.0/OPPS28.85-13-6/04442:user/release-keys'
#00 0x0004a1dc /system/lib/libc.so (tgkill+12)
#01 0x003929bb /data/app/com.tutpro.baresip-2806o0ACdhSoNhoZQSJEnw==/lib/arm/libbaresip.so
__aeabi_ldiv0
/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/lib1funcs.S:1337:0
#02 0x000a4378 /data/app/com.tutpro.baresip-2806o0ACdhSoNhoZQSJEnw==/lib/arm/libbaresip.so
audio_codec
/usr/src/libbaresip-android/baresip/src/audio.c:2304:6
Crash dump is completed

**Comment by juha-h** [comment]
juha-h writes:

> Unfortunately it turned out that after the timestamps were added,
> baresip is crashing on all Androind phones that have 32 bit
> armeabi-v7a cpu architecture:

Actually, the crashes occur already at commit:

https://github.com/alfredh/baresip/commit/3f2a18227adef0b4b9db2edc660c69862532bf2d

No crashed at previous commit:

https://github.com/alfredh/baresip/commit/915171ab791df8e87c40fff1780434455909057b

**Pull request merged**
