### PR TITLE
pulse: remove garbage at the beginning of a recording

### PR DESCRIPTION
**Pull request by glenvt18**
I've found that sometimes pa_simple_read() gets some garbage from my USB camera before 'real' samples arrive. This introduces an extra audio delay when calling baresip->baresip because a batch of packets (with real timestamps) is inserted at the beginning of the RTP stream. It happens randomly, usually after fast re-dials, and only when the USB camera's microphone is used (built-in analog input works fine). ALSA is not affected by this issue.

I propose a simple workaround for such cases which measures the time spent in pa_simple_read() and compares it to ptime.

Though, it's more a pulseaudio/driver issue, this workaround can be very helpful. In my case it dropped up to 50 packets (= 1 sec delay).

### CODE REVIEW

**Comment by alfredh** [comment]
the audio that is coming in the beginning, do you know if it contains silence
or garbage audio?

**Comment by glenvt18** [comment]
I don't know actually, and I don't care. What I see is a huge number of samples (20-40 ptime frames) being read in a very short interval (1-2 ms) right after the read thread starts. This results in a batch of RTP packets being sent almost instantly (can be seen in wireshark). After that, frames are being read at regular (~ptime) intervals. As the result, the audio is played by the receiver with a huge (up to 1 sec) delay. If I cut the initial burst out, the audio is played with a minimal delay.

As there is no noticeable delay between pulse_recorder_alloc() and the first pa_simple_read(), you are not expected to get 1 sec of audio at the first pa_simple_read() call. So, I consider it a pulseaudio/driver/device bug. It doesn't happen often, but the result (huge delay) is really nasty.

There is a chance that some 'real' samples could be thrown away by this method. I don't mind loosing several milliseconds at the beginning of the conversation. After all, pa_simple_new() takes some time (with my camera - up to 1 sec after being idle for a while).

The 'garbage' data are not really garbage. They look more like an low-level audio signal/noise, maybe leftovers from the previous session. If so, it's also a security issue:)

**Comment by alfredh** [comment]
Thank you :)

**Comment by glenvt18** [comment]
@alfredh How about moving pa_simple_new to read_thread to eliminate main loop stalls when the initialization takes a long time?

**Comment by alfredh** [comment]
The old ALSA module was opening the device from the context of the worker thread,
for the same reason. But we found some problems when using USB soundcards, where
sometimes it would not open the device successfully. So we changed it to always open
the device from the main thread (the current code).

However, if your suggested approach works with Pulse I am happy to test it out.

Alfred

**Pull request merged**
