### PR TITLE
Avcodec h264enc

### PR DESCRIPTION
**Pull request by alfredh**
this patch is an alternative to https://github.com/alfredh/baresip/pull/158

please review and test :)

@hargut

### CODE REVIEW

**Comment by hargut** [comment]
Tried to test it, but it seems that info/debug messages are not working in decode.c and encode.c.
So it's a bit hard to say what exactly is going on in there.

```
hargut@benchvice:~/Source/baresip.git$ ./baresip -v -e /vidloop
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=lxdbr0:10.0.0.11 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
avcodec: x264 build 148
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
avcodec: using h264 encoder by name (nvenc_h264)
vidsrc: avformat
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID a7eaa70b-877c-6095-f8c8-27b1770f8985 from file /home/hargut/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.

/vidloop
Enable video-loop on avformat,/home/hargut/dwhelper/st-pl.mp4: 352 x 288
vidloop: avformat,/home/hargut/dwhelper/st-pl.mp4: open video source: 352 x 288 at 500 fps
avformat: stream 0:  1280 x 720   time_base=1/50
vidloop: open video display (x11.nil)
reg: sip:hargut@home: Register: Destination address required
Quitus: [] []  intra=0  EFPS=34.0      376012 kbit/s       
ua: stop all (forced=0)
module: unloading app vidloop
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop
hargut@benchvice:~/Source/baresip.git$
```

I've also tried to replace debug with info in encode.c, but still no output for more details.
My feeling says that something is different compared to #151, but this might also be related to changes in vidloops frame handling.

Since FPS are nearly the same with and without hardware encoder active, it would be very helpful to see the debug messages.

**Comment by alfredh** [comment]
the `vidloop` command will not start the video codecs.

I just added a new command `vidloop_codec` which will enable the first codec
in the list. Could you please try that command ?

**Comment by hargut** [comment]
That looks good!

libx264 -> 7-8 fps
nvenc_h264 -> 24 fps

I'm just trying to recall, but did previously the "-evv" option trigger the codec as well?
A basic vidloop with -ev and codec enabled with another shortcut would be nice. "-e /vidloop_codec" is pretty long. ;-)

**Comment by hargut** [comment]
Some more details & logs:
[config.txt](https://github.com/alfredh/baresip/files/621416/config.txt)
```
hargut@benchvice:~/Source/baresip.git$ ffprobe /home/hargut/st-pl.mp4 
ffprobe version 3.0.2-1ubuntu7 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 6.2.0 (Ubuntu 6.2.0-5ubuntu11) 20160927
  configuration: --prefix=/usr --extra-version=1ubuntu7 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-nonfree --enable-nvenc --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu7 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-nonfree --enable-nvenc --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_amrwbenc
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/hargut/st-pl.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-08-20 12:21:00
  Duration: 00:04:16.14, start: 0.000000, bitrate: 1256 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1127 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
hargut@benchvice:~/Source/baresip.git$
```
without "avcodec_h264enc                nvenc_h264"
```
hargut@benchvice:~/Source/baresip.git$ ./baresip -e /vidloop_codec -v
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=lxdbr0:10.0.0.11 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
avcodec: using libavcodec H.264 encoder
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidsrc: avformat
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID a7eaa70b-877c-6095-f8c8-27b1770f8985 from file /home/hargut/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
/vidloop_codec
Enable video-loop on avformat,/home/hargut/dwhelper/st-pl.mp4: 352 x 288
vidloop: avformat,/home/hargut/dwhelper/st-pl.mp4: open video source: 352 x 288 at 500 fps
avformat: stream 0:  1280 x 720   time_base=1/50
vidloop: open video display (x11.nil)
vidloop: enabled encoder H264 (500 fps, 50000000 bit/s)
vidloop: enabled decoder H264
avcodec: video encoder H264: 500 fps, 50000000 bit/s, pktsize=1480
avcodec: video decoder H264 ()
Enabled codec: H264
[libx264 @ 0x7f898415df60] using cpu capabilities: MMX2 SSE2Fast LZCNT
[libx264 @ 0x7f898415df60] profile High, level 5.2
reg: sip:hargut@home: Register: Destination address required
Quitus: [H264] [H264]  intra=7  EFPS=5.4      1031 kbit/s       
ua: stop all (forced=0)
module: unloading app vidloop
[libx264 @ 0x7f898415df60] frame I:7     Avg QP:10.50  size: 28773
[libx264 @ 0x7f898415df60] frame P:60    Avg QP:11.29  size: 15089
[libx264 @ 0x7f898415df60] mb I  I16..4: 54.9% 33.2% 11.9%
[libx264 @ 0x7f898415df60] mb P  I16..4: 27.8% 13.8%  3.9%  P16..4: 18.5% 10.4%  2.6%  0.0%  0.0%    skip:22.9%
[libx264 @ 0x7f898415df60] final ratefactor: 7.84
[libx264 @ 0x7f898415df60] 8x8 transform intra:30.9% inter:53.1%
[libx264 @ 0x7f898415df60] coded y,uvDC,uvAC intra: 25.6% 24.5% 14.9% inter: 13.8% 12.1% 1.3%
[libx264 @ 0x7f898415df60] i16 v,h,dc,p: 72% 15%  6%  7%
[libx264 @ 0x7f898415df60] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 36% 18% 29%  2%  2%  3%  3%  3%  3%
[libx264 @ 0x7f898415df60] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 17% 21%  3%  5%  6%  5%  4%  3%
[libx264 @ 0x7f898415df60] i8c dc,h,v,p: 76%  9% 13%  2%
[libx264 @ 0x7f898415df60] Weighted P-Frames: Y:51.7% UV:0.0%
[libx264 @ 0x7f898415df60] kb/s:66073.13
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop
hargut@benchvice:~/Source/baresip.git$ 
```
with "avcodec_h264enc                nvenc_h264"
```
hargut@benchvice:~/Source/baresip.git$ ./baresip -e /vidloop_codec -v
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=lxdbr0:10.0.0.11 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
avcodec: using libavcodec H.264 encoder
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
avcodec: using h264 encoder by name (nvenc_h264)
vidsrc: avformat
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID a7eaa70b-877c-6095-f8c8-27b1770f8985 from file /home/hargut/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
/vidloop_codec
Enable video-loop on avformat,/home/hargut/dwhelper/st-pl.mp4: 352 x 288
vidloop: avformat,/home/hargut/dwhelper/st-pl.mp4: open video source: 352 x 288 at 500 fps
avformat: stream 0:  1280 x 720   time_base=1/50
vidloop: open video display (x11.nil)
vidloop: enabled encoder H264 (500 fps, 50000000 bit/s)
vidloop: enabled decoder H264
avcodec: h264 encoder activated
avcodec: video encoder H264: 500 fps, 50000000 bit/s, pktsize=1480
avcodec: video decoder H264 ()
Enabled codec: H264
avcodec: nvenc_h264 preset "llhp" selected
avcodec: nvenc_h264 option "2pass" selected
reg: sip:hargut@home: Register: Destination address required
Quitus: [H264] [H264]  intra=26  EFPS=22.9      11219 kbit/s       
ua: stop all (forced=0)
module: unloading app vidloop
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop
hargut@benchvice:~/Source/baresip.git$ 
```

Nice work. The patch works fine all the way through.

Thank you!

**Comment by alfredh** [comment]
@hargut thanks for your testing and feedback

**Comment by czarkoff** [comment]
@alfredh, why don't you just replace `vidloop` with `vidloop_codec`?

**Pull request merged**
