### PR TITLE
avcodec: add initial nvenc hardware encoding support

### PR DESCRIPTION
**Pull request by hargut**
Nvenc allows hardware encoding support for h264/h265 on various Nvidia graphic cards from Kepler & onwards hardware.

### CODE REVIEW

**Comment by hargut** [comment]
Just out of curiosity is there an easy way to run the same set of travis checks upfront creating a pull request?

Best regards,
Harald

**Comment by czarkoff** [comment]
@hargut: enable travis for your fork, I guess.

**Comment by alfredh** [comment]
this is a very nice patch

I am wondering if the "tryhwaccel" feature/option is generic enough to make it into the
baresip core.. keeping the changes local to the avcodec.so module would be a good start.
are there other video codec modules that will benefit from a shared "tryhwaccel" option?

in that case the config would be:

```
avcodec_tryhwaccel    yes
```

I dont have access to Nvidia hardware with H.264 acceleration. If you have tested the
code on such hardware, could you please include some technical details like logs,
average framerate/bitrate, name of hardware etc...

**Comment by hargut** [comment]
The tryhwaccel is something where I'm myself not sure what do do with it properly:
* I think it suits the modular and very high configurable design of baresip. Let the user choose if he wants to use graphic card acceleration or not.
* But why configure it anyways? I think most of the video players out there try to access the graphic card and simply use it if they succeeded.

Also I thought about doing it avcodec only, but ended up thinking:
Nvidia hardware can also do H265 encoding in hardware, which is right now implemented in different module. Intel can do hardware accelerated encoding on some platforms, but I have not looked into the details so far.
Further I know that there is still some bottle neck around, and at the moment I assume it is on the input/decode side. So we might end up in a situation where we need the option as well in avformat.

So the questions are:
* Is it required to have this option at all?
Only in case yes:
* For a single module or for all?

**Comment by hargut** [comment]
Used hardware for testing:
01:00.0 VGA compatible controller: NVIDIA Corporation GK208 [GeForce GT 730] (rev a1)
https://www.zotac.com/gb/product/graphics_card/gt-730-pcie-x1
This is a 60 Eur Graphic card, so nothing special, nothing fancy. Important is only GK (Kepler) or later.

FFmpeg from Ubuntu 16.10 compiled with nvidia_video_sdk_6.0.1:
```
hi  ffmpeg                                          7:3.0.2-1ubuntu7                            amd64        Tools for transcoding, streaming and playing of multimedia files
hi  ffmpeg-doc                                      7:3.0.2-1ubuntu7                            all          Documentation of the FFmpeg multimedia framework
hi  libav-tools                                     7:3.0.2-1ubuntu7                            all          Compatibility links for libav-tools (transitional package)
hi  libavcodec-dev:amd64                            7:3.0.2-1ubuntu7                            amd64        FFmpeg library with de/encoders for audio/video codecs - development files
hi  libavcodec-extra                                7:3.0.2-1ubuntu7                            all          FFmpeg library with extra codecs (metapackage)
hi  libavcodec-extra57:amd64                        7:3.0.2-1ubuntu7                            amd64        FFmpeg library with additional de/encoders for audio/video codecs
hi  libavdevice-dev:amd64                           7:3.0.2-1ubuntu7                            amd64        FFmpeg library for handling input and output devices - development files
hi  libavdevice57:amd64                             7:3.0.2-1ubuntu7                            amd64        FFmpeg library for handling input and output devices - runtime files
hi  libavfilter-dev:amd64                           7:3.0.2-1ubuntu7                            amd64        FFmpeg library containing media filters - development files
hi  libavfilter6:amd64                              7:3.0.2-1ubuntu7                            amd64        FFmpeg library containing media filters - runtime files
hi  libavformat-dev:amd64                           7:3.0.2-1ubuntu7                            amd64        FFmpeg library with (de)muxers for multimedia containers - development files
hi  libavformat57:amd64                             7:3.0.2-1ubuntu7                            amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
hi  libavresample-dev:amd64                         7:3.0.2-1ubuntu7                            amd64        FFmpeg compatibility library for resampling - development files
hi  libavresample3:amd64                            7:3.0.2-1ubuntu7                            amd64        FFmpeg compatibility library for resampling - runtime files
hi  libavutil-dev:amd64                             7:3.0.2-1ubuntu7                            amd64        FFmpeg library with functions for simplifying programming - development files
hi  libavutil55:amd64                               7:3.0.2-1ubuntu7                            amd64        FFmpeg library with functions for simplifying programming - runtime files
hi  libpostproc-dev:amd64                           7:3.0.2-1ubuntu7                            amd64        FFmpeg library for post processing - development files
hi  libpostproc54:amd64                             7:3.0.2-1ubuntu7                            amd64        FFmpeg library for post processing - runtime files
hi  libswresample-dev:amd64                         7:3.0.2-1ubuntu7                            amd64        FFmpeg library for audio resampling, rematrixing etc. - development files
hi  libswresample2:amd64                            7:3.0.2-1ubuntu7                            amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
hi  libswscale-dev:amd64                            7:3.0.2-1ubuntu7                            amd64        FFmpeg library for image scaling and various conversions - development files
hi  libswscale4:amd64                               7:3.0.2-1ubuntu7                            amd64        FFmpeg library for image scaling and various conversions - runtime files
```

Setup scenario for testing:
baresip with video input avformat, from mpeg4 source file.
```
video_source            avformat,/home/hargut/st-pl.mp4
video_display           x11,nil
video_size              352x288
video_bitrate           500000
video_fps               500
video_tryhwaccel        1
```

```
hargut@benchvice:~/baresip.hargut$ ./baresip -evv -v
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=lxdbr0:10.0.0.11 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
avcodec: using libavcodec H.264 encoder
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidsrc: avformat
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID a7eaa70b-877c-6095-f8c8-27b1770f8985 from file /home/hargut/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
Enable video-loop on avformat,/home/hargut/st-pl.mp4: 352 x 288
vidloop: avformat,/home/hargut/st-pl.mp4: open video source: 352 x 288 at 500 fps
avformat: stream 0:  1280 x 720   time_base=1/50
vidloop: open video display (x11.nil)
vidloop: enabled encoder H264 (500 fps, 500000 bit/s)
vidloop: enabled decoder H264
avcodec: tryhwaccel: 1
avcodec: nvenc_h264 encoder activated
avcodec: video encoder H264: 500 fps, 500000 bit/s, pktsize=1480
avcodec: video decoder H264 ()
Enabled codec: H264
avcodec: nvenc_h264 preset "llhp" selected
avcodec: nvenc_h264 option "2pass" selected
reg: sip:hargut@home: Register: Destination address required 
Quitus: [H264] [H264]  intra=53  EFPS=31.9      570 kbit/s       
ua: stop all (forced=0)
module: unloading app vidloop
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop
hargut@benchvice:~/baresip.hargut$
```

Setting video_tryhwaccel to 0 results in:
```
hargut@benchvice:~/baresip.hargut$ ./baresip -evv -v
baresip v0.5.0 Copyright (C) 2010 - 2016 Alfred E. Heggestad et al.
Local network address:  IPv4=lxdbr0:10.0.0.11 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
avcodec: using libavcodec H.264 encoder
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidsrc: avformat
vidisp: x11
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID a7eaa70b-877c-6095-f8c8-27b1770f8985 from file /home/hargut/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
Enable video-loop on avformat,/home/hargut/st-pl.mp4: 352 x 288
vidloop: avformat,/home/hargut/st-pl.mp4: open video source: 352 x 288 at 500 fps
avformat: stream 0:  1280 x 720   time_base=1/50
vidloop: open video display (x11.nil)
vidloop: enabled encoder H264 (500 fps, 500000 bit/s)
vidloop: enabled decoder H264
avcodec: tryhwaccel: 0
avcodec: video encoder H264: 500 fps, 500000 bit/s, pktsize=1480
avcodec: video decoder H264 ()
Enabled codec: H264
[libx264 @ 0x7f7e7015efa0] using cpu capabilities: MMX2 SSE2Fast LZCNT
[libx264 @ 0x7f7e7015efa0] profile High, level 5.2
reg: sip:hargut@home: Register: Destination address required 
Quitus: [H264] [H264]  intra=25  EFPS=14.9      86 kbit/s        
ua: stop all (forced=0)
module: unloading app vidloop
[libx264 @ 0x7f7e7015efa0] frame I:26    Avg QP:37.56  size:  5618
[libx264 @ 0x7f7e7015efa0] frame P:234   Avg QP:40.05  size:   223
[libx264 @ 0x7f7e7015efa0] mb I  I16..4: 91.1%  8.2%  0.7%
[libx264 @ 0x7f7e7015efa0] mb P  I16..4:  1.5%  0.0%  0.0%  P16..4:  1.2%  0.0%  0.0%  0.0%  0.0%    skip:97.2%
[libx264 @ 0x7f7e7015efa0] final ratefactor: 51.97
[libx264 @ 0x7f7e7015efa0] 8x8 transform intra:7.5% inter:75.4%
[libx264 @ 0x7f7e7015efa0] coded y,uvDC,uvAC intra: 1.7% 12.1% 0.0% inter: 0.0% 0.2% 0.0%
[libx264 @ 0x7f7e7015efa0] i16 v,h,dc,p: 58% 23%  5% 14%
[libx264 @ 0x7f7e7015efa0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 11%  6% 29% 16%  5%  5%  6% 16%  5%
[libx264 @ 0x7f7e7015efa0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 16% 28%  8%  9%  6%  6%  4%  3%
[libx264 @ 0x7f7e7015efa0] i8c dc,h,v,p: 91%  4%  5%  0%
[libx264 @ 0x7f7e7015efa0] Weighted P-Frames: Y:30.8% UV:18.4%
[libx264 @ 0x7f7e7015efa0] kb/s:3051.55
module: unloading app menu
menu: close (redial current_attempts=0)
module: unloading app debug_cmd
module: unloading app contact
module: unloading app auloop
Stopping 1 useragent.. 
ua: sip-stack exit
ua exited -- stopping main runloop
hargut@benchvice:~/baresip.hargut$
```

So on the same setup with same source we are talking about approx. 50% fps increase, but one has to say that the encoder "nvenc_h264" with preset "llhp" and "2pass" is not giving as good quality as the default libx264 encoder. "llhp" stands for low latency high performance. Therefore comparing fps in this case is a bit like comparing apples and pears.

But just to give you an impression what Nvidia's nvenc is able to do on a 60 Eur hardware, and this is also the reason why I assume that there is a bottleneck in avformat/avcodec:
Same source file, just ffmpeg for reencoding:
```
hargut@benchvice:~/baresip.hargut$ ffmpeg -probesize 8192 -i ~/st-pl.mp4 -codec:v nvenc_h264 -profile:v baseline -pix_fmt yuv420p -preset llhq -g 0 -b:v 5000k -codec:a mp2 -f mp4 tmp.mp4
ffmpeg version 3.0.2-1ubuntu7 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.2.0 (Ubuntu 6.2.0-5ubuntu11) 20160927
  configuration: --prefix=/usr --extra-version=1ubuntu7 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-nonfree --enable-nvenc --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu7 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-nonfree --enable-nvenc --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_amrwbenc
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/hargut/st-pl.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-08-20 12:21:00
  Duration: 00:04:16.14, start: 0.000000, bitrate: 1256 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1127 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmp.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf57.25.100
    Stream #0:0(und): Video: h264 (nvenc_h264) (Baseline) ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 5000 kb/s, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc57.24.102 nvenc_h264
    Side data:
      unknown side data type 10 (24 bytes)
    Stream #0:1(und): Audio: mp2 (i[0][0][0] / 0x0069), 44100 Hz, stereo, s16, 384 kb/s (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc57.24.102 mp2
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (nvenc_h264))
  Stream #0:1 -> #0:1 (aac (native) -> mp2 (native))
Press [q] to stop, [?] for help
frame= 1049 fps=187 q=-0.0 Lsize=   28152kB time=00:00:41.99 bitrate=5491.8kbits/s speed=7.49x    
video:26152kB audio:1969kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.111346%```

**Comment by hargut** [comment]
And for nearly reasonable comparsion with libx264:
```
hargut@benchvice:~/baresip.hargut$ ffmpeg -probesize 8192 -i ~/st-pl.mp4 -codec:v libx264 -profile:v baseline -pix_fmt yuv420p -g 0 -b:v 5000k -tune zerolatency -codec:a mp2 -f mp4 tmp.mp4
ffmpeg version 3.0.2-1ubuntu7 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.2.0 (Ubuntu 6.2.0-5ubuntu11) 20160927
  configuration: --prefix=/usr --extra-version=1ubuntu7 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-nonfree --enable-nvenc --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu7 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-nonfree --enable-nvenc --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264 --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_amrwbenc
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/hargut/st-pl.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-08-20 12:21:00
  Duration: 00:04:16.14, start: 0.000000, bitrate: 1256 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1127 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
[libx264 @ 0x562b046526e0] using SAR=1/1
[libx264 @ 0x562b046526e0] using cpu capabilities: MMX2 SSE2Fast LZCNT
[libx264 @ 0x562b046526e0] profile Constrained Baseline, level 3.1
[libx264 @ 0x562b046526e0] 264 - core 148 r2699 a5e06b9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=1 keyint_min=1 scenecut=40 intra_refresh=0 rc=abr mbtree=0 bitrate=5000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'tmp.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf57.25.100
    Stream #0:0(und): Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 5000 kb/s, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc57.24.102 libx264
    Side data:
      unknown side data type 10 (24 bytes)
    Stream #0:1(und): Audio: mp2 (i[0][0][0] / 0x0069), 44100 Hz, stereo, s16, 384 kb/s (default)
    Metadata:
      creation_time   : 2016-08-20 12:21:00
      handler_name    : ISO Media file produced by Google Inc.
      encoder         : Lavc57.24.102 mp2
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> mp2 (native))
Press [q] to stop, [?] for help
frame=  771 fps= 43 q=27.0 Lsize=   20330kB time=00:00:30.84 bitrate=5400.2kbits/s speed=1.73x    
video:18858kB audio:1446kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.126109%
[libx264 @ 0x562b046526e0] frame I:771   Avg QP:23.29  size: 25046
[libx264 @ 0x562b046526e0] mb I  I16..4: 63.3%  0.0% 36.7%
[libx264 @ 0x562b046526e0] final ratefactor: 24.27
[libx264 @ 0x562b046526e0] coded y,uvDC,uvAC intra: 30.2% 51.8% 4.8%
[libx264 @ 0x562b046526e0] i16 v,h,dc,p: 38% 21% 13% 27%
[libx264 @ 0x562b046526e0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 25% 20% 24%  7%  5%  4%  5%  6%  4%
[libx264 @ 0x562b046526e0] i8c dc,h,v,p: 60% 16% 19%  5%
[libx264 @ 0x562b046526e0] kb/s:5009.11
hargut@benchvice:~/baresip.hargut$ 
```

**Comment by alfredh** [comment]
let us try to keep the changes only in the `avcodec` module for now.

when running `ffmpeg -codecs` on my Debian box:

```
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_crystalhd h264_vdpau ) (encoders: libx264 libx264rgb h264_vaapi )
```

to make it more flexible, we could perhaps make the codec name configurable?

example:

```
avcodec_h264_encoder        h264_vaapi
avcodec_h264_decoder        h264_vdpau
```

**Comment by czarkoff** [comment]
FWIW I find the first approach much more useful.  Can it be generalized to other codecs as well?  There might be hardware acceleration for other codecs...

**Comment by hargut** [comment]
A generic option setting the en-/decoder in avcodec_find_encoder_by_name() will most likely not work out properly for many of them. Especially when looking at it from the hardware acceleration perspective.

Vdpau / vaapi need more setup than selecting the encoder to get hardware accelerated decoding/encoding running.
Unfortunately it seems that nvenc is probably one rare case where hardware acceleration works as simple as that. I think on OSX it would be also that straight forward. For crystalhd I'm not sure, but vaapi & vdpau require additional work.

**Comment by hargut** [comment]
How about doing something like:
```
switch (avcodec_h264_decoder) {
   case vdpau_h264:
      hwaccel =  HWACCEL_NVIDIA;
      init_vdpau();
      set_decoder_vdpau();
      break;
   case vaapi:
      hwaccel =  HWACCEL_VAAPI;
      init_vaapi();
      set_decoder_vaapi();
      break;
   case unconfigured:
      break; //do what we do now
   default:
      warning("Using encoder %s as requested. ", avcodec_h264_decoder);
      warning("The selected decoder is untested and might be setup incorrectly.\n", avcodec_h264_decoder);
      st->codec = avcodec_find_encoder_by_name(avcodec_h264_decoder));
      break;
}
```
This would allow flexibility during selection & support all encoders/decoders which do not need additional setup.

**Comment by alfredh** [comment]
Hi @hargut very good idea.

yesterday I tested h264 videotoolbox on my OSX and it works fine as HWACCEL :)
this means that there are multiple options for HW-accellerated encoders, also
depending on platform of course.

I dont think we should add support for all HWACCEL's in this PR, but rather be
pragmatic and add support for the ones that can be tested.

I dont like the solution of "try" hwaccel first and fallback to software encoding
if that fails, this kind of solution is a bit fragile. I would prefer explicit config,
and that the user has configured exactly what he wants and if that encoder fails,
then it should fail.

the option name should match the name from FFmpeg, and the codec name
should be resolved when the module is loaded, i.e. inside `module_init()`.

example:

```
avcodec_h264enc    h264 | libx264 | nvenc_264 | h264_toolbox
```

**Comment by alfredh** [comment]
@hargut I have made a new patch based on your patch, could you please test it:

https://github.com/alfredh/baresip/tree/avcodec_h264enc


Example config:
```
avcodec_h264enc    nvenc_h264
```

**Comment by hargut** [comment]
Final "initial" implementation for avformat_h264enc support in #181.
Therefore closing this pull request.

Thank you very much for integrating & updating this initial version.

**Pull request closed without merging**
