### PR TITLE
aptx: 24-bit audio i/o support (S24_3LE)

### PR DESCRIPTION
**Pull request by premultiply**

### CODE REVIEW

**Comment by alfredh** [comment]
there are some ccheck warnings that needs to be fixed:

./modules/aptx/encode.c:95: line is too wide (83 - max 79)
1580

**Comment by premultiply** [comment]
Yes I saw it but the funny thing is that it seems that only the tab/space-calculation of the checker is wrong.

**Comment by alfredh** [comment]
I tested the patch and it works well, tested both S16 and S24_3LE sample format.

**Comment by alfredh** [comment]
I am ready to merge the patch, if you can fix the ccheck warnings.

The ccheck.py tool assumes that a TAB is 8 spaces.

**Comment by premultiply** [comment]
Isn't it a bit too much?
Normal TAB-spacing is 4 spaces.

**Pull request merged**
