### PR TITLE
add numeric version number

### PR DESCRIPTION
**Pull request by paresy**
Submitting a PR as requested in https://github.com/alfredh/baresip/issues/893

Thanks!

### CODE REVIEW

**Comment by alfredh** [comment]
the master version number is kept in the Makefile:

https://github.com/alfredh/baresip/blob/master/Makefile#L13

for every version bump, we run make version:

```
$ make version
updating version number to 0.6.5
```

which updates the version number in baresip.h

would it perhaps be easier to define:

```
#define BARESIP_VERSION_MAJOR 0
#define BARESIP_VERSION_MINOR 6
#define BARESIP_VERSION_PATCH 5
```

**Comment by paresy** [comment]
Sure that should also work well. 

If i understood correctly at the moment you bump the BARESIP_VERSION_STRING define and run "make version" to update references.

I can update the Makefile magic to properly update your proposed splitted defines or would you prefer to update the splitted defines by hand and then run the Makefile magic to automatically update the BARESIP_VERSION_STRING and other references?

The second variant should be easier to implement/maintain but would imply a small workflow change. Is this documented somewhere? If yes, i can update the docs as well.

**Comment by alfredh** [comment]
I was thinking something like this:


Makefile:

old:

```
VERSION   := 0.6.5
```


new:

```
# Master version number
VER_MAJOR := 0
VER_MINOR := 6
VER_PATCH := 5

VERSION   := $(VER_MAJOR).$(VER_MINOR).$(VER_PATCH)
```

and then update the "make version" target with
the 3 sub-version numbers.

**Comment by alfredh** [comment]
please reopen when you have a new patch

**Pull request closed without merging**
