### PR TITLE
avformat: improve video_fps handling

### PR DESCRIPTION
**Pull request by hargut**
#208

### CODE REVIEW

**Comment by alfredh** [comment]
many thanks for your patch.

the PR contains a `core` file , this must be removed before merging.

**Comment by alfredh** [comment]
I have tested your patch with a Timecode display:

http://www.mediacollege.com/downloads/video/timecode/clock.html

the timing is very accurate.

**Comment by alfredh** [comment]
some warnings on OSX 10.6:

```
modules/avformat/avformat.c: In function ‘read_thread’:
modules/avformat/avformat.c:200: warning: ISO C90 forbids mixed declarations and code
modules/avformat/avformat.c: In function ‘alloc’:
modules/avformat/avformat.c:345: warning: implicit conversion shortens 64-bit value into a 32-bit value
```

**Comment by hargut** [comment]
Both should be fixed now. :-)

**Comment by alfredh** [comment]
Hello Harald, your patch was merged.

Many thanks for this work, it was many people that complained about blocking sleep :)


/Alfred

**Comment by hargut** [comment]
Thanks for merging.

**Pull request merged**
