### PR TITLE
ua: add support for SIP trace

### PR DESCRIPTION
**Pull request by alfredh**
this requires a special version of libre:

  https://github.com/alfredh/re

To run baresip with SIP trace enabled:

```
$ baresip -i
```

(the letter `i` is open to better ideas).

### CODE REVIEW

**Comment by alfredh** [comment]
sip-trace

**Comment by juha-h** [comment]
Thanks, good feature for testing.  Why is special version of libre needed, i.e., why can't trace support be included in the standard libre?

**Comment by alfredh** [comment]
do you have any opinion of the `i` letter ? it was reused from `curl`:

```
       -i, --include
              Include the HTTP response headers in the output. The HTTP response headers can
              include things like server name, cookies, date of the document,  HTTP  version
              and more...

```

we can use a different letter if you have better suggestions.

the feature is experimental for now, hence special version of libre.

**Comment by juha-h** [comment]
How about -s (for sip trace)?

As long as this new feature does not affect SIP protocol operation of re, it could still be included there even if it experimental.  It does not really matter if printing of SIP messages to console has some defects.

**Comment by alfredh** [comment]
thanks for your input, I changed it to -s and merged it to master.

we might include it in re master later ..

**Pull request merged**
