### PR TITLE
opengles android ndk r18 update

### PR DESCRIPTION
**Pull request by juha-h**
Added GL_GLEXT_PROTOTYPES CFLAGS define so that functions are found in header file.
Changed include file path.

### CODE REVIEW

**Comment by alfredh** [comment]
compilation fails on ios:

modules/opengles/opengles.c:10:10: fatal error: 'GLES/gl.h' file not found

**Comment by alfredh** [comment]
Tested on iOS and Android:

iOS: compile and link OK
Android: compile OK, linking Failed

```
make[1]: Entering directory '/home/alfredh/git/baresip-android/baresip'
  SH      src/static.c
  CC      build-arm/src/static.o
  CC [m]  build-arm/modules/opengles/opengles.o
  LD      baresip
modules/opengles/opengles.c:32: error: undefined reference to 'glGenTextures'
modules/opengles/opengles.c:36: error: undefined reference to 'glBindTexture'
modules/opengles/opengles.c:37: error: undefined reference to 'glTexParameterf'
modules/opengles/opengles.c:38: error: undefined reference to 'glTexImage2D'
modules/opengles/opengles.c:41: error: undefined reference to 'glTexParameteri'
modules/opengles/opengles.c:42: error: undefined reference to 'glTexParameteri'
modules/opengles/opengles.c:43: error: undefined reference to 'glTexParameterf'
modules/opengles/opengles.c:44: error: undefined reference to 'glTexParameterf'
modules/opengles/opengles.c:45: error: undefined reference to 'glBindTexture'
modules/opengles/opengles.c:60: error: undefined reference to 'glBindTexture'
modules/opengles/opengles.c:62: error: undefined reference to 'glTexImage2D'
modules/opengles/opengles.c:67: error: undefined reference to 'glEnableClientState'
modules/opengles/opengles.c:68: error: undefined reference to 'glVertexPointer'
modules/opengles/opengles.c:71: error: undefined reference to 'glEnableClientState'
modules/opengles/opengles.c:72: error: undefined reference to 'glTexCoordPointer'
modules/opengles/opengles.c:74: error: undefined reference to 'glBindTexture'
modules/opengles/opengles.c:76: error: undefined reference to 'glEnable'
modules/opengles/opengles.c:77: error: undefined reference to 'glTexParameteri'
modules/opengles/opengles.c:78: error: undefined reference to 'glTexParameteri'
modules/opengles/opengles.c:79: error: undefined reference to 'glTexParameterf'
modules/opengles/opengles.c:81: error: undefined reference to 'glDrawArrays'
modules/opengles/opengles.c:82: error: undefined reference to 'glDisable'
```

(Android NDK r16b, API 21).


the android version does not link to anything:

```
#
# module.mk
#
# Copyright (C) 2010 Creytiv.com
#

MOD		:= opengles
$(MOD)_SRCS	+= opengles.c

ifeq ($(OS),darwin)
$(MOD)_SRCS	+= context.m

$(MOD)_LFLAGS	+= -lobjc -framework CoreGraphics -framework CoreFoundation
endif

include mk/mod.mk
```

perhaps that needs to be added also.

I have the following GL-related libraries in my NDK:

```
-rwxr-xr-x 1 alfredh alfredh   13176 Dec  1  2017 libEGL.so
-rwxr-xr-x 1 alfredh alfredh   55180 Dec  1  2017 libGLESv1_CM.so
-rwxr-xr-x 1 alfredh alfredh   45064 Dec  1  2017 libGLESv2.so
-rwxr-xr-x 1 alfredh alfredh   75004 Dec  1  2017 libGLESv3.so
```

**Comment by alfredh** [comment]
adding this helps a bit:

```
$(MOD)_LFLAGS   += -lGLESv2 -lGLESv1_CM
```

but still undefined reference to `context_xxx` functions

if I remember correctly, those 3 functions has to be implemented
in the module, or use ifdef when invoked.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:
> adding this helps a bit:
> 
> ```
> $(MOD)_LFLAGS   += -lGLESv2 -lGLESv1_CM
> ```
> 
> but still undefined reference to `context_xxx` functions
> 
> if I remember correctly, those 3 functions has to be implemented
> in the module, or use ifdef when invoked.

I get the same errors in Android Studio after I added GLESv2 and
GLESv1_CM to CMakeLists.txt target_link_libraries:
```
modules/opengles/opengles.c:241: error: undefined reference to 'context_init'
modules/opengles/opengles.c:276: error: undefined reference to 'context_render'
modules/opengles/opengles.c:216: error: undefined reference to 'context_destroy'
```

**Comment by alfredh** [comment]
perhaps we could add ifdef DARWIN to the code invoking those functions:

```c
#ifdef DARWIN
	err = context_init(st);
	if (err)
		goto out;
#endif
```

this would at least make the module compile and link.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> perhaps we could add ifdef DARWIN to the code invoking those functions:
> 
> ```c
> #ifdef DARWIN
> 	err = context_init(st);
> 	if (err)
> 		goto out;
> #endif
> ```
> this would at least make the module compile and link.

What is the purpose of the context_* functions.  Would the module work
without them?

**Comment by alfredh** [comment]
it has to do with the Window/View for iOS.

this is now a long time ago, but I remember that it was needed for iOS.

I am not sure if they are needed for Android or not, I dont have any
way to test it here.

BTW: opengles is now deprecated in iOS and replaced by something
called "Metal". Hopefully someone comes along and writes a video
driver for metal.

**Comment by juha-h** [comment]
I updated the pull request with FLAGS and ifdef'ed context_* calls.

**Comment by alfredh** [comment]
Thanks! compile-tested on iOS and Android.

**Pull request merged**
