### PR TITLE
Fix ringback and call waiting sounds coming from alert device

### PR DESCRIPTION
**Pull request by gblair**
This is an attempt to address #934, and I encountered the "call waiting" discrepancy while I was at it. Thanks!

### CODE REVIEW

**Comment by alfredh** [comment]
thanks for the patch, this looks quite good

couple of things to fix:

1. test code, run "make test" and fix build errors and run-time errors

2. ccheck warnings. see Travis CI for details.

**Comment by gblair** [comment]
Thanks @alfredh! I should be able to get these bits done in the next couple of days.

**Comment by gblair** [comment]
💦 ok I _think_ that takes care of it, but let me know. Thanks again!

**Comment by gblair** [comment]
One last update: just rebased on top your your latest `master` for convenience ;)

**Comment by alfredh** [comment]
merged. many thanks for your contributions :)

**Pull request merged**
