### PR TITLE
ua: do ua_register explicitly (refs #508)

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by alfredh** [comment]
@juha-h please review and test

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> @juha-h please review and test

I built baresip from branch ua_alloc_register.  Build went fine, but
menu module load fails:

dl: mod: /usr/lib/baresip/modules/menu.so (/usr/lib/baresip/modules/menu.so: undefined symbol: mediadev_print)
module menu.so: No such file or directory

**Comment by alfredh** [comment]
mediadev.c was added.

can you try a clean build?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> mediadev.c was added.
> 
> can you try a clean build?

I did like this:

 2065  cd orig/baresip/
 2066  git branch
 2067  git pull
 2068  dpkg-buildpackage -rfakeroot -b -us -uc
 2069  cd ..
 2070  sudo dpkg -i baresip_0.5.10_amd64.deb 
 2071  baresip

and in above, git branch gave:

$ git branch
  empty_contacts_file
  master
  message_ua
* ua_alloc_register

Isn't that a clean build?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> mediadev.c was added.

This file exists, but menu.so still tells that mediadev_print is
undefined:

$ git checkout ua_alloc_register
Already on 'ua_alloc_register'
Your branch is up-to-date with 'origin/ua_alloc_register'.
$ git pull
Current branch ua_alloc_register is up to date.
$ find . -name mediadev.c -print
./src/mediadev.c
$ make clean
$ make distclean
$ dpkg-buildpackage -rfakeroot -b -us -uc
$ cd ..
$ sudo dpkg -i baresip_0.5.10_amd64.deb
$ baresip
...
dl: mod: /usr/lib/baresip/modules/menu.so (/usr/lib/baresip/modules/menu.so: undefined symbol: mediadev_print)
module menu.so: No such file or directory

**Comment by alfredh** [comment]
this is a bit strange.

can you try the same debian package with master branch and see if it works ?

or try a manual build of baresip ?

on my Debian machine the symbol is present:

```
$ nm libbaresip.a | grep mediadev
mediadev.o:
0000000000000010 T mediadev_add
00000000000000a0 T mediadev_find
0000000000000100 T mediadev_get_default
0000000000000140 T mediadev_print
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> this is a bit strange.

My bad like most of the time.  I had another baresip in /usr/local/bin.

Now branch 'ua_alloc_register' works fine:

$ baresip
...
test@test.tutpro.com: Using sipnat: `outbound'
test@test.tutpro.com: Using media encryption `zrtp'
ua: SIP register failed: Network is unreachable
account: failed to register ua (Network is unreachable)
module account.so: Network is unreachable
Populated 0 contacts
...
baresip is ready.
net: local IPv4 address changed: 127.0.0.1 -> 192.168.43.107
IP-address changed: 192.168.43.107
test@test.tutpro.com: {1/TCP/v4} 200 OK (OpenSIPg SIP Proxy (5.2.0-0a06 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (60029 ms)

**Comment by alfredh** [comment]
great, okay to merge it now ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> great, okay to merge it now ?

Yes,

**Pull request merged**
