### PR TITLE
use sipsess_offer_handler also for UPDATE request offers

### PR DESCRIPTION
**Pull request by juha-h**

### CODE REVIEW

**Comment by juha-h** [comment]
Added to pull request new version of zrtp module that is now aligned with latest libzrtp from Freeswitch.
- zrtp_cache_set_verified is now zrtp_verified_set
- local zid is not anymore included in zrtp_config and needs to be given
   as argument to zrtp_verified_set
- zrtp_config.cache_file_cfg is now zrtp_config.def_cache_path

**Comment by alfredh** [comment]
could you please create a separate PR for the zrtp changes?

in your baresip fork you can have multiple branches, and a new PR can be issued
from a specific branch.

**Comment by juha-h** [comment]
This will be replaced by two pull requests.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> could you please create a separate PR for the zrtp changes?

Should be done now (separate pull requests on UPDATE and ZRTP).

-- Juha

**Pull request closed without merging**
