### PR TITLE
AAC codec

### PR DESCRIPTION
**Pull request by alfredh**
Add support for AAC audio codec.

Install AAC FDK:

`$ sudo apt-get install libfdk-aac-dev`

or

`$ brew install fdk-aac`

For now only samplerate 48000Hz and 1 channel is supported.
Profile: AAC-LD (Low Delay).

### CODE REVIEW

**Comment by alfredh** [comment]
Tested on:

* OSX 10.12 with fdk-aac 2.0.0
* Debian 10 with libfdk-aac1 0.1.6-1
* Debian 10 with valgrind and libfdk-aac1 0.1.6-1

**Comment by premultiply** [comment]
For the moment this seems to be at least incompatible with professional codecs as they use other SIP descriptions (https://tools.ietf.org/html/rfc3640) like this:


```
Orban Opticodec 7600 Setting "AAC (MPEG2)":
#
U 192.168.0.10:5060 -> 192.168.0.30:42786
INVITE sip:1069155266620-0x8a63f0@192.168.0.30:42786 SIP/2.0.
Via: SIP/2.0/UDP 192.168.0.10:5060;branch=z9hG4bKou5klh20cgomev4lo500.1.
From: "OPTICODEC7600" <sip:1069155242902@192.168.0.10>;tag=IxlON0mA.
To: <sip:1069155266620@192.168.0.20>.
Call-ID: 1lTpzcGEYzie4PAG.
CSeq: 29304 INVITE.
Contact: <sip:1069155242902-rrgh531oo5664@192.168.0.10:5060;transport=udp>.
Max-Forwards: 67.
User-Agent: Opticodec7600/5.11.115.
Content-Type: application/sdp.
Allow: INVITE, ACK, CANCEL, BYE, OPTIONS.
Content-Length: 284.
.
v=0.
o=OC7600 1213378870 1 IN IP4 192.168.8.250.
s=audio.
c=IN IP4 192.168.8.250.
t=0 0.
m=audio 5004 RTP/AVP 96 9 8 0.
a=rtpmap:96 MPA/90000.
a=fmtp:96 layer=4;samplerate=48000;bitrate=128000;mode=stereo.
a=rtpmap:9 G722/8000.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=sendrecv.



Orban Opticodec 7600 Setting "AAC (MPEG4)":
#
U 192.168.0.10:5060 -> 192.168.0.30:38821
INVITE sip:1069155266620-0x15a13f0@192.168.0.30:38821 SIP/2.0.
Via: SIP/2.0/UDP 192.168.0.10:5060;branch=z9hG4bKctmlsi206od0e116i400.1.
From: "OPTICODEC7600" <sip:1069155242902@192.168.0.10>;tag=vp2KqPDT.
To: <sip:1069155266620@192.168.0.20>.
Call-ID: dKkyND0qeOLzcZKy.
CSeq: 14271 INVITE.
Contact: <sip:1069155242902-rrgh531oo5664@192.168.0.10:5060;transport=udp>.
Max-Forwards: 67.
User-Agent: Opticodec7600/5.11.115.
Content-Type: application/sdp.
Allow: INVITE, ACK, CANCEL, BYE, OPTIONS.
Content-Length: 356.
.
v=0.
o=OC7600 2039503094 1 IN IP4 192.168.8.250.
s=audio.
c=IN IP4 192.168.8.250.
t=0 0.
m=audio 5004 RTP/AVP 96.
b=TIAS:128000.
a=maxprate:46.875.
a=rtpmap:96 mpeg4-generic/48000/2.
a=fmtp:96 streamtype=5; profile-level-id=16; config=1190; mode=aac-hbr; constantduration=1024; sizelength=13; indexlength=3; indexdeltalength=3; bitrate=128000.
a=sendrecv.



Orban Opticodec 7600 Setting "AAC LD":
#
U 192.168.0.10:5060 -> 192.168.0.30:38821
INVITE sip:1069155266620-0x15a13f0@192.168.0.30:38821 SIP/2.0.
Via: SIP/2.0/UDP 192.168.0.10:5060;branch=z9hG4bKvgn61g00c85kp51gg200.1.
From: "OPTICODEC7600" <sip:1069155242902@192.168.0.10>;tag=eQLb7qf6.
To: <sip:1069155266620@192.168.0.20>.
Call-ID: hyzB2DKHv5pyzqx1.
CSeq: 27617 INVITE.
Contact: <sip:1069155242902-rrgh531oo5664@192.168.0.10:5060;transport=udp>.
Max-Forwards: 67.
User-Agent: Opticodec7600/5.11.115.
Content-Type: application/sdp.
Allow: INVITE, ACK, CANCEL, BYE, OPTIONS.
Content-Length: 356.
.
v=0.
o=OC7600 373550335 1 IN IP4 192.168.8.250.
s=audio.
c=IN IP4 192.168.8.250.
t=0 0.
m=audio 5004 RTP/AVP 96.
b=TIAS:128000.
a=maxprate:46.875.
a=rtpmap:96 mpeg4-generic/48000/2.
a=fmtp:96 streamtype=5; profile-level-id=25; config=B99500; mode=aac-hbr; constantduration=480; sizelength=13; indexlength=3; indexdeltalength=3; bitrate=128000.
a=sendrecv.



Orban Opticodec 7600 Setting "AAC HE":
#
U 192.168.0.10:5060 -> 192.168.0.30:38821
INVITE sip:1069155266620-0x15a13f0@192.168.0.30:38821 SIP/2.0.
Via: SIP/2.0/UDP 192.168.0.10:5060;branch=z9hG4bKgrp2lm20281b63dri200.1.
From: "OPTICODEC7600" <sip:1069155242902@192.168.0.10>;tag=Qu+X6wIU.
To: <sip:1069155266620@192.168.0.20>.
Call-ID: 2zeV-mvAND6rP90k.
CSeq: 39662 INVITE.
Contact: <sip:1069155242902-rrgh531oo5664@192.168.0.10:5060;transport=udp>.
Max-Forwards: 67.
User-Agent: Opticodec7600/5.11.115.
Content-Type: application/sdp.
Allow: INVITE, ACK, CANCEL, BYE, OPTIONS.
Content-Length: 359.
.
v=0.
o=OC7600 509174766 1 IN IP4 192.168.8.250.
s=audio.
c=IN IP4 192.168.8.250.
t=0 0.
m=audio 5004 RTP/AVP 96.
b=TIAS:128000.
a=maxprate:23.437.
a=rtpmap:96 mpeg4-generic/48000/2.
a=fmtp:96 streamtype=5; profile-level-id=46; config=2B118800; mode=aac-hbr; constantduration=2048; sizelength=13; indexlength=3; indexdeltalength=3; bitrate=128000.
a=sendrecv.



Orban Opticodec 7600 Setting "AAC HEv2":
#
U 192.168.0.10:5060 -> 192.168.0.30:38821
INVITE sip:1069155266620-0x15a13f0@192.168.0.30:38821 SIP/2.0.
Via: SIP/2.0/UDP 192.168.0.10:5060;branch=z9hG4bKckli13004gdjntkca300.1.
From: "OPTICODEC7600" <sip:1069155242902@192.168.0.10>;tag=91JQ-LKN.
To: <sip:1069155266620@192.168.0.20>.
Call-ID: jwpT552r7XcwHCHm.
CSeq: 27068 INVITE.
Contact: <sip:1069155242902-rrgh531oo5664@192.168.0.10:5060;transport=udp>.
Max-Forwards: 67.
User-Agent: Opticodec7600/5.11.115.
Content-Type: application/sdp.
Allow: INVITE, ACK, CANCEL, BYE, OPTIONS.
Content-Length: 357.
.
v=0.
o=OC7600 368334818 1 IN IP4 192.168.8.250.
s=audio.
c=IN IP4 192.168.8.250.
t=0 0.
m=audio 5004 RTP/AVP 96.
b=TIAS:64000.
a=maxprate:23.437.
a=rtpmap:96 mpeg4-generic/48000/2.
a=fmtp:96 streamtype=5; profile-level-id=49; config=EB098800; mode=aac-hbr; constantduration=2048; sizelength=13; indexlength=3; indexdeltalength=3; bitrate=64000.
a=sendrecv.



baresip 0.6.4 with AAC:
#
U 192.168.0.30:38821 -> 192.168.0.10:5060
INVITE sip:1069155242902@192.168.0.10 SIP/2.0.
Via: SIP/2.0/UDP 192.168.0.30:38821;branch=z9hG4bK642d4108468f89e5;rport.
Contact: <sip:1069155266620-0x15a13f0@192.168.0.30:38821>.
Max-Forwards: 70.
To: <sip:1069155242902@192.168.0.10>.
From: <sip:1069155266620@192.168.0.10>;tag=4c65960f5e707c0b.
Call-ID: 64a7d9256f676dd6.
CSeq: 24828 INVITE.
User-Agent: baresip v0.6.4 (arm6/linux).
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Supported: gruu.
Content-Type: application/sdp.
Content-Length: 939.
.
v=0.
o=- 376403993 351750254 IN IP4 192.168.0.30.
s=-.
c=IN IP4 192.168.0.30.
t=0 0.
a=tool:baresip 0.6.4.
m=audio 31714 RTP/AVP 96 97 14 98 10 99 100 101 102 11 103 104 105 106.
a=rtpmap:96 opus/48000/2.
a=fmtp:96 stereo=1;sprop-stereo=1;maxaveragebitrate=320000;cbr=1;useinbandfec=0;usedtx=0.
a=rtpmap:97 MP4A-LATM/90000.
a=fmtp:97 profile-level-id=24;object=23;bitrate=64000.
a=rtpmap:14 MPA/90000.
a=fmtp:14 layer=3;samplerate=48000;bitrate=320000;mode=stereo.
a=rtpmap:98 L16/48000/2.
a=rtpmap:10 L16/44100/2.
a=rtpmap:99 L16/32000/2.
a=rtpmap:100 L16/16000/2.
a=rtpmap:101 L16/8000/2.
a=rtpmap:102 L16/48000.
a=rtpmap:11 L16/44100.
a=rtpmap:103 L16/32000.
a=rtpmap:104 L16/16000.
a=rtpmap:105 L16/8000.
a=rtpmap:106 telephone-event/8000.
a=fmtp:106 0-15.
a=sendrecv.
a=label:1.
a=rtcp-rsize.
a=ssrc:1962481865 cname:sip:1069155266620@192.168.0.10.
a=rtcp-mux.
a=ptime:20.
a=ebuacip:version 0.
a=ebuacip:jb 0.
a=ebuacip:qosrec 46
#
U 192.168.0.10:5060 -> 192.168.0.30:38821
SIP/2.0 100 Trying.
Via: SIP/2.0/UDP 192.168.0.30:38821;received=192.168.0.20;branch=z9hG4bK642d4108468f89e5;rport=38821.
To: <sip:1069155242902@192.168.0.10>.
From: <sip:1069155266620@192.168.0.10>;tag=4c65960f5e707c0b.
Call-ID: 64a7d9256f676dd6.
CSeq: 24828 INVITE.
.
```

**Comment by alfredh** [comment]
can you try to change the payload name in aac.c to this:

`mpeg4-generic`

```c
static struct aucodec aac = {
	.name      = "MP4A-LATM",
	.srate     = AAC_SRATE,
	.crate     = 90000,
	.ch        = AAC_CHANNELS,
	.pch       = 1,
	.encupdh   = aac_encode_update,
	.ench      = aac_encode_frm,
	.decupdh   = aac_decode_update,
	.dech      = aac_decode_frm,
	.fmtp_ench = aac_fmtp_enc,
	.fmtp_cmph = aac_fmtp_cmp,
};
```

it might also be that you have to change the value here, in aac/encode.c:

```c
	error |= aacEncoder_SetParam(aes->enc, AACENC_AOT, AOT_ER_AAC_LD);
```

to a different value, see `/usr/local/include/fdk-aac/FDK_audio.h`

**Comment by premultiply** [comment]
I already looked into this but I came to the conclusion that it would require much more modifications and extensions as `mpeg4-generic` does for example does not use LATM and the encoder and SDP fmtp needs far more parameters. I already linked to the RFC und EBU documents in the roadmap page.

And as with all the dynamic formats there should be a parameter mirroring for tx as callee.

But this is far above my personal C coding capabilities. :-(

**Comment by alfredh** [comment]
ok i can perhaps make a
patch if you can help with
testing on your equipment.

i tested with Cisco videoconf box.

**Comment by premultiply** [comment]
Shure!

**Comment by premultiply** [comment]
Can we rename this module to MP4A or even MP4A-LATM?
Just AAC is a bit misleading as there may be at least two more modules providing other types, signalisation and transport of AAC audio in the near future.

**Pull request merged**
